//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFT_ClubHouse__Management.Libs.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GFT_ClubHouse__Management.Libs.Language.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required!.
        /// </summary>
        public static string MSG_E001 {
            get {
                return ResourceManager.GetString("MSG_E001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field must be at least {1} characters..
        /// </summary>
        public static string MSG_E002 {
            get {
                return ResourceManager.GetString("MSG_E002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field must be a maximum of {1} characters..
        /// </summary>
        public static string MSG_E003 {
            get {
                return ResourceManager.GetString("MSG_E003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field was not filled in correctly..
        /// </summary>
        public static string MSG_E004 {
            get {
                return ResourceManager.GetString("MSG_E004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the {0} field does not match the value of the {1} field..
        /// </summary>
        public static string MSG_E005 {
            get {
                return ResourceManager.GetString("MSG_E005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The E-Mail informed has been used previously..
        /// </summary>
        public static string MSG_E006 {
            get {
                return ResourceManager.GetString("MSG_E006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oopss .. There was an error while performing the operation. Try again later..
        /// </summary>
        public static string MSG_E007 {
            get {
                return ResourceManager.GetString("MSG_E007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials! Check and try again..
        /// </summary>
        public static string MSG_E008 {
            get {
                return ResourceManager.GetString("MSG_E008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied!.
        /// </summary>
        public static string MSG_E009 {
            get {
                return ResourceManager.GetString("MSG_E009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email you entered is not registered in our system. Check and try again..
        /// </summary>
        public static string MSG_E010 {
            get {
                return ResourceManager.GetString("MSG_E010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the {0} field must be between {1} and {2}..
        /// </summary>
        public static string MSG_E011 {
            get {
                return ResourceManager.GetString("MSG_E011", resourceCulture);
            }
        }
    }
}
