// <auto-generated />
using System;
using GFT_ClubHouse__Management.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GFT_ClubHouse__Management.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200207145520_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GFT_ClubHouse__Management.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(12);

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<string>("Zip")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("GFT_ClubHouse__Management.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Capacity");

                    b.Property<DateTime>("Date");

                    b.Property<int>("HouseClubId");

                    b.Property<int>("MusicalGenreId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<double>("Price");

                    b.HasKey("Id");

                    b.HasIndex("HouseClubId");

                    b.HasIndex("MusicalGenreId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("GFT_ClubHouse__Management.Models.HouseClub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AddressId");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("HouseClubs");
                });

            modelBuilder.Entity("GFT_ClubHouse__Management.Models.MusicalGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.HasKey("Id");

                    b.ToTable("MusicalGenres");
                });

            modelBuilder.Entity("GFT_ClubHouse__Management.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AddressId");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("LastName");

                    b.Property<string>("Name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<string>("Phone")
                        .IsRequired();

                    b.Property<int>("Roles");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GFT_ClubHouse__Management.Models.Event", b =>
                {
                    b.HasOne("GFT_ClubHouse__Management.Models.HouseClub", "HouseClub")
                        .WithMany()
                        .HasForeignKey("HouseClubId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GFT_ClubHouse__Management.Models.MusicalGenre", "MusicalGenre")
                        .WithMany()
                        .HasForeignKey("MusicalGenreId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GFT_ClubHouse__Management.Models.HouseClub", b =>
                {
                    b.HasOne("GFT_ClubHouse__Management.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GFT_ClubHouse__Management.Models.User", b =>
                {
                    b.HasOne("GFT_ClubHouse__Management.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
